module.exports={
  'status':{
                  'HTTP_200_OK':200,
                  'HTTP_201_CREATED':201,
                  'HTTP_202_ACCEPTED':202,
                  'HTTP_400_BAD_REQUEST':400,
                  'HTTP_404_NOT_FOUND':404,
                  'HTTP_405_NOT_ALLOWED':405,
                  'HTTP_500_INTERNAL_ERROR':500
                },
    'method':{
                'GET':'GET',
                'POST':'POST',
                'PATCH':'PATCH',
                'DELETE':'DELETE'
              }
};
